//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ACUCOBOL.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ACUCOBOLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IACUCOBOLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] ACUCOBOLParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] ACUCOBOLParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.dataDivision"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataDivision([NotNull] ACUCOBOLParser.DataDivisionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.dataDivision"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataDivision([NotNull] ACUCOBOLParser.DataDivisionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.workingStorageSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWorkingStorageSection([NotNull] ACUCOBOLParser.WorkingStorageSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.workingStorageSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWorkingStorageSection([NotNull] ACUCOBOLParser.WorkingStorageSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.fileSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileSection([NotNull] ACUCOBOLParser.FileSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.fileSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileSection([NotNull] ACUCOBOLParser.FileSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.fileDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileDescription([NotNull] ACUCOBOLParser.FileDescriptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.fileDescription"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileDescription([NotNull] ACUCOBOLParser.FileDescriptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.recordDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordDeclaration([NotNull] ACUCOBOLParser.RecordDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.recordDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordDeclaration([NotNull] ACUCOBOLParser.RecordDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.linkageSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinkageSection([NotNull] ACUCOBOLParser.LinkageSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.linkageSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinkageSection([NotNull] ACUCOBOLParser.LinkageSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] ACUCOBOLParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] ACUCOBOLParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.procedureDivision"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureDivision([NotNull] ACUCOBOLParser.ProcedureDivisionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.procedureDivision"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureDivision([NotNull] ACUCOBOLParser.ProcedureDivisionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.paragraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParagraph([NotNull] ACUCOBOLParser.ParagraphContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.paragraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParagraph([NotNull] ACUCOBOLParser.ParagraphContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.paragraphName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParagraphName([NotNull] ACUCOBOLParser.ParagraphNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.paragraphName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParagraphName([NotNull] ACUCOBOLParser.ParagraphNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.sentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentence([NotNull] ACUCOBOLParser.SentenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.sentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentence([NotNull] ACUCOBOLParser.SentenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] ACUCOBOLParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] ACUCOBOLParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.moveStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoveStatement([NotNull] ACUCOBOLParser.MoveStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.moveStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoveStatement([NotNull] ACUCOBOLParser.MoveStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.displayStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplayStatement([NotNull] ACUCOBOLParser.DisplayStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.displayStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplayStatement([NotNull] ACUCOBOLParser.DisplayStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.sqlStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSqlStatement([NotNull] ACUCOBOLParser.SqlStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.sqlStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSqlStatement([NotNull] ACUCOBOLParser.SqlStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.sqlConnect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSqlConnect([NotNull] ACUCOBOLParser.SqlConnectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.sqlConnect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSqlConnect([NotNull] ACUCOBOLParser.SqlConnectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.sqlQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSqlQuery([NotNull] ACUCOBOLParser.SqlQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.sqlQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSqlQuery([NotNull] ACUCOBOLParser.SqlQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallStatement([NotNull] ACUCOBOLParser.CallStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallStatement([NotNull] ACUCOBOLParser.CallStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.stopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStopStatement([NotNull] ACUCOBOLParser.StopStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.stopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStopStatement([NotNull] ACUCOBOLParser.StopStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.gobackStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGobackStatement([NotNull] ACUCOBOLParser.GobackStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.gobackStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGobackStatement([NotNull] ACUCOBOLParser.GobackStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] ACUCOBOLParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] ACUCOBOLParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.performStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPerformStatement([NotNull] ACUCOBOLParser.PerformStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.performStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPerformStatement([NotNull] ACUCOBOLParser.PerformStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.startValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartValue([NotNull] ACUCOBOLParser.StartValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.startValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartValue([NotNull] ACUCOBOLParser.StartValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.initialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitialValue([NotNull] ACUCOBOLParser.InitialValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.initialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitialValue([NotNull] ACUCOBOLParser.InitialValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.incrementValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncrementValue([NotNull] ACUCOBOLParser.IncrementValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.incrementValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncrementValue([NotNull] ACUCOBOLParser.IncrementValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.endValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndValue([NotNull] ACUCOBOLParser.EndValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.endValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndValue([NotNull] ACUCOBOLParser.EndValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.fileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileStatement([NotNull] ACUCOBOLParser.FileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.fileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileStatement([NotNull] ACUCOBOLParser.FileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.copyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCopyStatement([NotNull] ACUCOBOLParser.CopyStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.copyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCopyStatement([NotNull] ACUCOBOLParser.CopyStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.computeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComputeStatement([NotNull] ACUCOBOLParser.ComputeStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.computeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComputeStatement([NotNull] ACUCOBOLParser.ComputeStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.stringStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringStatement([NotNull] ACUCOBOLParser.StringStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.stringStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringStatement([NotNull] ACUCOBOLParser.StringStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.acceptStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAcceptStatement([NotNull] ACUCOBOLParser.AcceptStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.acceptStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAcceptStatement([NotNull] ACUCOBOLParser.AcceptStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] ACUCOBOLParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] ACUCOBOLParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] ACUCOBOLParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] ACUCOBOLParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] ACUCOBOLParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] ACUCOBOLParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] ACUCOBOLParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] ACUCOBOLParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] ACUCOBOLParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] ACUCOBOLParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] ACUCOBOLParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] ACUCOBOLParser.ConstantContext context);
}
