//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ACUCOBOL.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IACUCOBOLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ACUCOBOLBaseListener : IACUCOBOLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] ACUCOBOLParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] ACUCOBOLParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.dataDivision"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataDivision([NotNull] ACUCOBOLParser.DataDivisionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.dataDivision"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataDivision([NotNull] ACUCOBOLParser.DataDivisionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.workingStorageSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWorkingStorageSection([NotNull] ACUCOBOLParser.WorkingStorageSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.workingStorageSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWorkingStorageSection([NotNull] ACUCOBOLParser.WorkingStorageSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.fileSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileSection([NotNull] ACUCOBOLParser.FileSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.fileSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileSection([NotNull] ACUCOBOLParser.FileSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.fileDescription"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileDescription([NotNull] ACUCOBOLParser.FileDescriptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.fileDescription"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileDescription([NotNull] ACUCOBOLParser.FileDescriptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.recordDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordDeclaration([NotNull] ACUCOBOLParser.RecordDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.recordDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordDeclaration([NotNull] ACUCOBOLParser.RecordDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.linkageSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinkageSection([NotNull] ACUCOBOLParser.LinkageSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.linkageSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinkageSection([NotNull] ACUCOBOLParser.LinkageSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] ACUCOBOLParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] ACUCOBOLParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.procedureDivision"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureDivision([NotNull] ACUCOBOLParser.ProcedureDivisionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.procedureDivision"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureDivision([NotNull] ACUCOBOLParser.ProcedureDivisionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.paragraph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParagraph([NotNull] ACUCOBOLParser.ParagraphContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.paragraph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParagraph([NotNull] ACUCOBOLParser.ParagraphContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.paragraphName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParagraphName([NotNull] ACUCOBOLParser.ParagraphNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.paragraphName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParagraphName([NotNull] ACUCOBOLParser.ParagraphNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.sentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentence([NotNull] ACUCOBOLParser.SentenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.sentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentence([NotNull] ACUCOBOLParser.SentenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] ACUCOBOLParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] ACUCOBOLParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.moveStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveStatement([NotNull] ACUCOBOLParser.MoveStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.moveStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveStatement([NotNull] ACUCOBOLParser.MoveStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.displayStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplayStatement([NotNull] ACUCOBOLParser.DisplayStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.displayStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplayStatement([NotNull] ACUCOBOLParser.DisplayStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.sqlStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSqlStatement([NotNull] ACUCOBOLParser.SqlStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.sqlStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSqlStatement([NotNull] ACUCOBOLParser.SqlStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.sqlConnect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSqlConnect([NotNull] ACUCOBOLParser.SqlConnectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.sqlConnect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSqlConnect([NotNull] ACUCOBOLParser.SqlConnectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.sqlQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSqlQuery([NotNull] ACUCOBOLParser.SqlQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.sqlQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSqlQuery([NotNull] ACUCOBOLParser.SqlQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallStatement([NotNull] ACUCOBOLParser.CallStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallStatement([NotNull] ACUCOBOLParser.CallStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.stopStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStopStatement([NotNull] ACUCOBOLParser.StopStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.stopStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStopStatement([NotNull] ACUCOBOLParser.StopStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.gobackStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGobackStatement([NotNull] ACUCOBOLParser.GobackStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.gobackStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGobackStatement([NotNull] ACUCOBOLParser.GobackStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] ACUCOBOLParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] ACUCOBOLParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.performStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPerformStatement([NotNull] ACUCOBOLParser.PerformStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.performStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPerformStatement([NotNull] ACUCOBOLParser.PerformStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.startValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStartValue([NotNull] ACUCOBOLParser.StartValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.startValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStartValue([NotNull] ACUCOBOLParser.StartValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.initialValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitialValue([NotNull] ACUCOBOLParser.InitialValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.initialValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitialValue([NotNull] ACUCOBOLParser.InitialValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.incrementValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncrementValue([NotNull] ACUCOBOLParser.IncrementValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.incrementValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncrementValue([NotNull] ACUCOBOLParser.IncrementValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.endValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndValue([NotNull] ACUCOBOLParser.EndValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.endValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndValue([NotNull] ACUCOBOLParser.EndValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.fileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileStatement([NotNull] ACUCOBOLParser.FileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.fileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileStatement([NotNull] ACUCOBOLParser.FileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.copyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCopyStatement([NotNull] ACUCOBOLParser.CopyStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.copyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCopyStatement([NotNull] ACUCOBOLParser.CopyStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.computeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComputeStatement([NotNull] ACUCOBOLParser.ComputeStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.computeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComputeStatement([NotNull] ACUCOBOLParser.ComputeStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.stringStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringStatement([NotNull] ACUCOBOLParser.StringStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.stringStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringStatement([NotNull] ACUCOBOLParser.StringStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.acceptStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAcceptStatement([NotNull] ACUCOBOLParser.AcceptStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.acceptStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAcceptStatement([NotNull] ACUCOBOLParser.AcceptStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] ACUCOBOLParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] ACUCOBOLParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] ACUCOBOLParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] ACUCOBOLParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] ACUCOBOLParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] ACUCOBOLParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] ACUCOBOLParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] ACUCOBOLParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] ACUCOBOLParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] ACUCOBOLParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ACUCOBOLParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] ACUCOBOLParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ACUCOBOLParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] ACUCOBOLParser.ConstantContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
